build:
    nodes:
        coverage:
            tests:
                override:
                    - node db/setup.js
                    - npm run cleandb
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
        services:
            mongo: 4
    environment:
        mongodb: true
    services:
        mongo: 4
